  
name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://github.com/npm/npm-registry-couchapp
      - run: npm install && npm run build
      - uses: phips28/gh-action-bump-version@master
      - run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
